name: kotaemon
channels:
  - conda-forge
dependencies:
  - bzip2
  - ca-certificates
  - libffi
  - libsqlite
  - libzlib
  - ncurses
  - openssl
  - pip
  - python=3.10
  - readline
  - setuptools
  - tk
  - wheel
  - xz
  - pip:
      - aiofiles
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - alabaster
      - annotated-types
      - anyio
      - arrow
      - asgiref
      - asttokens
      - async-timeout
      - attrs
      - azure-ai-documentintelligence
      - azure-core
      - babel
      - backoff
      - bcrypt
      - beautifulsoup4
      - binaryornot
      - black
      - build
      - cachetools
      - certifi
      - cfgv
      - chardet
      - charset-normalizer
      - chroma-hnswlib
      - chromadb
      - click
      - cohere
      - coloredlogs
      - colorlog
      - contourpy
      - cookiecutter
      - coverage
      - cycler
      - dataclasses-json
      - decorator
      - deprecated
      - deprecation
      - dirtyjson
      - diskcache
      - distlib
      - distro
      - docutils
      - duckduckgo-search
      - elastic-transport
      - elasticsearch
      - et-xmlfile
      - exceptiongroup
      - executing
      - fast-langdetect
      - fastapi
      - fastavro
      - fasttext-wheel
      - ffmpy
      - filelock
      - flake8
      - flatbuffers
      - fonttools
      - frozenlist
      - fsspec
      - google-auth
      - googleapis-common-protos
      - googlesearch-python
      - gradio
      - gradio-client
      - greenlet
      - grpcio
      - h11
      - html2text
      - httpcore
      - httptools
      - httpx
      - httpx-sse
      - huggingface-hub
      - humanfriendly
      - identify
      - idna
      - imagesize
      - importlib-metadata
      - importlib-resources
      - iniconfig
      - ipython
      - isodate
      - jedi
      - jinja2
      - jiter
      - joblib
      - jsonpatch
      - jsonpointer
      - kiwisolver
      - kotaemon@git+https://github.com/Cinnamon/kotaemon.git@main#subdirectory=libs/kotaemon
      - ktem@git+https://github.com/Cinnamon/kotaemon.git@main#subdirectory=libs/ktem
      - kubernetes
      - lancedb
      - langchain
      - langchain-community
      - langchain-core
      - langchain-openai
      - langchain-text-splitters
      - langsmith
      - linkify-it-py
      - llama-cloud
      - llama-hub
      - llama-index
      - llama-index-agent-openai
      - llama-index-cli
      - llama-index-core
      - llama-index-embeddings-openai
      - llama-index-indices-managed-llama-cloud
      - llama-index-legacy
      - llama-index-llms-openai
      - llama-index-multi-modal-llms-openai
      - llama-index-program-openai
      - llama-index-question-gen-openai
      - llama-index-readers-file
      - llama-index-readers-llama-parse
      - llama-index-vector-stores-chroma
      - llama-index-vector-stores-lancedb
      - llama-parse
      - lxml
      - markdown
      - markdown-it-py
      - markupsafe
      - marshmallow
      - matplotlib
      - matplotlib-inline
      - mccabe
      - mdit-py-plugins
      - mdurl
      - mmh3
      - monotonic
      - mpmath
      - multidict
      - mypy-extensions
      - nest-asyncio
      - networkx
      - nltk
      - nodeenv
      - numpy
      - oauthlib
      - onnxruntime
      - openai
      - openpyxl
      - opentelemetry-api
      - opentelemetry-exporter-otlp-proto-common
      - opentelemetry-exporter-otlp-proto-grpc
      - opentelemetry-instrumentation
      - opentelemetry-instrumentation-asgi
      - opentelemetry-instrumentation-fastapi
      - opentelemetry-proto
      - opentelemetry-sdk
      - opentelemetry-semantic-conventions
      - opentelemetry-util-http
      - orjson
      - overrides
      - packaging
      - pandas
      - parso
      - pathspec
      - pexpect
      - pillow
      - platformdirs
      - plotly
      - pluggy
      - posthog
      - pre-commit
      - prompt-toolkit
      - protobuf
      - psutil
      - ptyprocess
      - pure-eval
      - py
      - pyaml
      - pyarrow
      - pyasn1
      - pyasn1-modules
      - pybind11
      - pycodestyle
      - pydantic
      - pydantic-core
      - pydub
      - pyflakes
      - pygments
      - pylance
      - pymupdf
      - pymupdfb
      - pyparsing
      - pypdf
      - pypika
      - pyproject-hooks
      - pyreqwest-impersonate
      - pytest
      - pytest-mock
      - python-dateutil
      - python-decouple
      - python-docx
      - python-dotenv
      - python-multipart
      - python-slugify
      - pytz
      - pyyaml
      - ratelimiter
      - regex
      - requests
      - requests-oauthlib
      - retry
      - retrying
      - rich
      - robust-downloader
      - rsa
      - ruff
      - semantic-version
      - shellingham
      - six
      - sniffio
      - snowballstemmer
      - soupsieve
      - sphinx
      - sphinxcontrib-applehelp
      - sphinxcontrib-devhelp
      - sphinxcontrib-htmlhelp
      - sphinxcontrib-jsmath
      - sphinxcontrib-qthelp
      - sphinxcontrib-serializinghtml
      - sqlalchemy
      - sqlmodel
      - stack-data
      - starlette
      - striprtf
      - sympy
      - tabulate
      - tantivy
      - tenacity
      - text-unidecode
      - textual
      - theflow
      - tiktoken
      - tokenizers
      - tomli
      - tomlkit
      - tqdm
      - traitlets
      - trogon
      - typer
      - types-python-dateutil
      - types-requests
      - typing-extensions
      - typing-inspect
      - tzdata
      - uc-micro-py
      - urllib3
      - uvicorn
      - uvloop
      - virtualenv
      - watchfiles
      - wcwidth
      - websocket-client
      - websockets
      - wikipedia
      - wrapt
      - yarl
      - zipp
